[phases.setup]
nixPkgs = ["maven", "openjdk17"]

[phases.build]
cmds = ["mvn clean package -DskipTests"]

[phases.start]
cmd = "java -Dserver.port=$PORT -Dspring.profiles.active=production -jar target/online-banking-system-0.0.1-SNAPSHOT.jar"
