[build]
builder = "NIXPACKS"

[deploy]
startCommand = "java -Dserver.port=$PORT -Dspring.profiles.active=h2 -jar target/online-banking-system-0.0.1-SNAPSHOT.jar"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
